In [2]:
import numpy as np

## creating arrays using numpy
arr1 = np.array([1,2,3,4,5])
print(arr1)


[1 2 3 4 5]


In [3]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [4]:
arr2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [7]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
arr = np.array([[1,2,3], [4,5,6]])

print("array:\n", arr)
print("shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Size (number of elements):", arr.size)
print("data type:", arr.dtype)
print("Item size (in bytes):", arr.itemsize)

array:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
data type: int64
Item size (in bytes): 8


In [14]:
## numpy Vectorised Operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Element wise addition
print("addition:",arr1+arr2)

addition: [11 22 33 44 55]


In [16]:
## Universal functions
arr = np.array(([2,3,4,5,6]))

print(np.sqrt(arr))
print(np.sin(arr))
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [37]:
## array slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(np.ndim(arr))
print("shape:", arr.shape)
print("array: \n", arr)

2
shape: (3, 4)
array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
arr[0][0]

np.int64(1)

In [35]:
arr[0:2 , 2:]

array([[3, 4],
       [7, 8]])

In [36]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [39]:
arr[1: , 1:3]

array([[ 6,  7],
       [10, 11]])

In [40]:
## Statistical concept - Normalisation
## to have a mean of 0 and have a sd of 1

data = np.array([1,2,3,4,5])

## calculate the mean and sd
mean = np.mean(data)
sd = np.std(data)

## Normalise the data
normalised_data = (data - mean) / sd
print("normalised data: ", normalised_data)


normalised data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
